<?xml version="1.0" encoding="utf-8"?><Database Name="Transactions" Class="TransactionsDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Transactions.mdf;Integrated Security=True" SettingsObjectName="Accounting.Properties.Settings" SettingsPropertyName="TransactionsConnectionString" Provider="System.Data.SqlClient" />
</Database>